name: semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
    
jobs:
  secuirycheck:
    name: upload semgrep scanning result
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create results 
        run: |
          mkdir results
          chmod +w results

      - name: Install semgrep
        run: |
          pip3 install semgrep          

      - name: Run Semgrep
        run: semgrep scan --config auto --sarif --output results/results.sarif .
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results/results.sarif
          category: semgrep
